### ISSUE TITLE
embed.loadFlatScore not loading after initial new Flat.Embed call

### ISSUE THREAD

**Issue by dloker** [FlatIO/embed-client#38]
I am trying out flatIO js embed for the first time and created a few simple tests on my localhost. I'm running `python -m http.server` to start the webserver locally.

The code I'm executing is as follows:
```
var container = document.getElementById('embed-container');
var embed = new Flat.Embed(container, {
  embedParams: {
    appId: '<appId>'
  }
});

embed.loadFlatScore('56ae21579a127715a02901a6');
```

Also, I had to use a personal token instead of appId to get anything to work at all. I'm not sure why that is. If I load the score during `new Flat.Embed`, it loads up fine. But, if I do it after, it doesn't work. In fact, any commands I perform on embed after the initial creation do not work. I tried loading music xml, flat score, fullscreen, etc.

I have an appId and personal token.

In the console of the browser (I've tried Chrome and Safari) I see the following:
```
[Error] Failed to load resource: the server responded with a status of 403 (HTTP/2.0 403) (vendor.embed.min.js.map, line 0)
[Error] Failed to load resource: the server responded with a status of 403 (HTTP/2.0 403) (raven.min.js.map, line 0)
[Error] Failed to load resource: the server responded with a status of 403 (HTTP/2.0 403) (adagio.min.js.map, line 0)
[Error] Failed to load resource: the server responded with a status of 403 (HTTP/2.0 403) (dacapo.min.js.map, line 0)
[Error] Failed to load resource: the server responded with a status of 403 (HTTP/2.0 403) (flat.common.min.js.map, line 0)
[Error] Failed to load resource: the server responded with a status of 403 (HTTP/2.0 403) (flat.embed.min.js.map, line 0)
[Error] Failed to load resource: the server responded with a status of 403 (HTTP/2.0 403) (flat.embed.jsapi.min.js.map, line 0)
```

**Comment by gierschv** [comment]
Hi David,

Thanks for your issue. The app id is available on the main page of our developer dashboard. At this time, our jsAPI requires to whitelist the origins domains that will use it, could you please send us the info at developers@flat.io, options not yet available in your UI.

Vincent

**Comment by dloker** [comment]
I'm not sure what you mean by the developer dashboard. But, in My Apps section, I do have an AppId and I used it. It just didn't work. I had to use my personal token to get anything to work at all.

Good to know about the white listing issue, I'd probably put that in a comment somewhere so that people know that ahead of time. Also, I don't have a domain I'm using from yet, I was trying to test out the feature set to understand if I want to spend time developing around your system. Thus, I was using localhost. Sounds like that's going to be an issue for me.

Thanks!

**Comment by gierschv** [comment]
Thanks again for the feedback. I just updated the [README with clear info regarding the App ID](https://github.com/FlatIO/embed-client/blob/master/README.md#app-id):
* `localhost` / `*.localhost` are now whitelisted and can be used having to pass an `appId`
* you can now directly update the domain whitelist for this JS Client on our website (Apps > Embed > Settings):

![](https://cl.ly/3w3V2y3a2X09/Screen%20Shot%202017-10-18%20at%2017.02.40.png)
