### ISSUE TITLE
TypeError: l['$adagio-location'] is undefined

### ISSUE THREAD

**Issue by jenia0jenia** [FlatIO/embed-client#402]
I have an error in my embed .mxl

`[error] TypeError: l['$adagio-location'] is undefined`

and here is link (SECOND frame)...
[http://elib.pl.spb.ru/search_result_full?data=eyJ0eXBlX3MiOiBbIjEyMDAwIl0sICJ0ZXJtIjogWyJkZjBmZmFlZDc4NDBmZjQzYzhiYzJhYmQxOTRhYTA0MiJdfQ==#nota](http://elib.pl.spb.ru/search_result_full?data=eyJ0eXBlX3MiOiBbIjEyMDAwIl0sICJ0ZXJtIjogWyJkZjBmZmFlZDc4NDBmZjQzYzhiYzJhYmQxOTRhYTA0MiJdfQ==#nota)

But it is absolutely correct when I import .mxl to flat.io
[https://flat.io/score/65573383c1ff184a0775b637-stehe-still](https://flat.io/score/65573383c1ff184a0775b637-stehe-still)

firefox 119.0.1 x64

(in chrome I have another error `[Vue warn]: Error in 5: "TypeError: Cannot read properties of undefined (reading 'timePos')"`)

**Comment by gierschv** [comment]
@cyrilcoutelier Can you please check?

**Comment by cyrilcoutelier** [comment]
Hi @jenia0jenia ,

The link you sent, `http://elib.pl.spb.ru/search_result_full?data=eyJ0eXBlX3MiOiBbIjEyMDAwIl0sICJ0ZXJtIjogWyJkZjBmZmFlZDc4NDBmZjQzYzhiYzJhYmQxOTRhYTA0MiJdfQ==#nota`, is not working for me. 

I will need more context. 
Can you give me more context on how you are using our Embed API? This way it will be easier for us to reproduce 
the issue, and either fix it on our side, or explain the correct API usage. 

Thank you in advance! 
Best,
Cyril

**Comment by gierschv** [comment]
Closing, issue inactive for more than 1 year.
